# Generated by Django 5.2.8 on 2025-11-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherquery',
            options={},
        ),
        migrations.AddField(
            model_name='weatherquery',
            name='unit',
            field=models.CharField(default='metric', max_length=8),
        ),
    ]
