# Generated by Django 5.2.8 on 2025-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_weatherquery_options_weatherquery_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='weatherquery',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='weatherquery',
            name='from_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='unit',
            field=models.CharField(default='metric', max_length=10),
        ),
    ]
